Create an order for a selected service
julianoviedo1/planit pull request #11
Opened 2021-05-24 20:01 UTC by julianoviedo1

Orders Form View:

![image](https://user-images.githubusercontent.com/57849907/119401187-887c1a80-bcb1-11eb-9934-e0a676c18824.png)

Still needs back-end features

2021-05-28 18:07 UTC, julianoviedo1 commented on app/controllers/services_controller.rb
> +    # @order = @service.orders.new
This has not worked, but i think it should. Isnt it?

2021-05-28 18:08 UTC, julianoviedo1 commented on app/controllers/services_controller.rb
> +    # @order = @service.orders.new
Solved

2021-05-28 18:43 UTC, julianoviedo1 commented
Form result:

![image](https://user-images.githubusercontent.com/57849907/120028729-7230d000-bfcb-11eb-88f1-cd0b25e40417.png)

2021-05-28 21:29 UTC, jpbalarini requested changes

2021-05-28 21:29 UTC, jpbalarini commented on app/controllers/orders_controller.rb
> +    @order.status = 'pending'
there's too much logic in this method. The best thing would be to create a private method to do all this. Something like `build_order` maybe?

2021-05-28 21:29 UTC, jpbalarini commented on app/views/services/show.html.erb
>      <h6 class="fw-bold letter-spacing py-4 text-dark fs-6 mx-4">INVITADOS</h6>
indentation doesn't look good here (should be inside the form)

2021-05-31 16:41 UTC, julianoviedo1 commented on app/views/services/show.html.erb
>      <h6 class="fw-bold letter-spacing py-4 text-dark fs-6 mx-4">INVITADOS</h6>
Resoslved in commit: 83ad4ae

2021-05-31 16:42 UTC, julianoviedo1 commented on app/controllers/orders_controller.rb
> +    @order.status = 'pending'
Resolved in commit: 96a6668

2021-06-03 15:02 UTC, jpbalarini approved these changes
👍

2021-06-03 15:17 UTC, merged