Initial project configuration
julianoviedo1/planit pull request #2
Opened 2021-05-06 19:47 UTC by julianoviedo1

Migrations, associations created.
validations and seeds are incomplete.

Check story in: https://trello.com/c/tncTAwSw

2021-05-06 20:01 UTC, jpbalarini requested changes
Great work so far! A couple of general comments:
- On each model we have this comment:
```
# frozen_string_literal: true

# Service to download ftp files from the server
```
let's remove that since it does not apply here

- Remove the auto generated tests since we are going to use factories (instead of fixtures) and rspec instead of testcases

2021-05-06 20:01 UTC, jpbalarini commented on config/database.yml
>  default: &default
we don't usually commit the `database.yml` file since it could be different for each user (different ports, configuration, db name, etc). You can leave it for now since you are the only one using this repo

2021-05-06 20:01 UTC, jpbalarini commented on db/migrate/20210506173433_create_suppliers.rb
> +      t.string :name
let's add an index to the name. It's something we are going to constantly search for (supplier by name)

2021-05-06 20:01 UTC, jpbalarini commented on db/migrate/20210506173456_create_services.rb
> +      t.string :name
same here as above

2021-05-06 20:01 UTC, jpbalarini commented on db/migrate/20210506173545_create_categories.rb
> +      t.string :name
same

2021-05-06 20:01 UTC, jpbalarini commented on db/migrate/20210506173705_create_orders.rb
> +      t.integer :status
let's add an index to the status. It will be something common to check orders with status = X

2021-05-06 20:01 UTC, jpbalarini commented on db/seeds.rb
> +
please remove unnecessary newlines

2021-05-07 15:02 UTC, julianoviedo1 commented on db/migrate/20210506173705_create_orders.rb
> +      t.integer :status
Perfect, done in commit: 3c3ae1b

2021-05-07 15:03 UTC, julianoviedo1 commented on db/migrate/20210506173545_create_categories.rb
> +      t.string :name
Perfect, done in commit: 3c3ae1b

2021-05-07 15:03 UTC, julianoviedo1 commented on db/migrate/20210506173456_create_services.rb
> +      t.string :name
Perfect, done in commit: 3c3ae1b

2021-05-07 15:03 UTC, julianoviedo1 commented on db/migrate/20210506173433_create_suppliers.rb
> +      t.string :name
Perfect, done in commit: 3c3ae1b

2021-05-07 15:04 UTC, julianoviedo1 commented on config/database.yml
>  default: &default
Okey then, i ll take it into account next time.

2021-05-07 15:30 UTC, merged